language: node_js
node_js:
  - "0.10"
notifications:
  email:
    on_success: "never"
before_install:
  - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
script:
  - "npm run pretest && BROWSER=ff npm run cover"
